using UnityEngine;
using UnityEditor;
using Mirror;
using TacticalCombat.Combat;

namespace TacticalCombat.Editor
{
    /// <summary>
    /// ✅ NEW: Fixes Weapon prefabs by adding NetworkIdentity if missing
    /// </summary>
    public class WeaponPrefabFixer : EditorWindow
    {
        [MenuItem("TacticalCombat/Tools/Fix Weapon Prefabs (Add NetworkIdentity)")]
        public static void ShowWindow()
        {
            GetWindow<WeaponPrefabFixer>("Weapon Prefab Fixer");
        }

        private void OnGUI()
        {
            GUILayout.Label("Weapon Prefab Fixer", EditorStyles.boldLabel);
            GUILayout.Space(10);

            EditorGUILayout.HelpBox(
                "This tool will:\n" +
                "1. Find all prefabs with WeaponSystem component\n" +
                "2. Add NetworkIdentity if missing\n" +
                "3. Fix network settings",
                MessageType.Info
            );

            GUILayout.Space(10);

            if (GUILayout.Button("Fix All Weapon Prefabs", GUILayout.Height(30)))
            {
                FixAllWeaponPrefabs();
            }

            GUILayout.Space(10);

            if (GUILayout.Button("Fix Selected Prefabs", GUILayout.Height(30)))
            {
                FixSelectedPrefabs();
            }
        }

        private void FixAllWeaponPrefabs()
        {
            // Find all prefabs with WeaponSystem
            string[] guids = AssetDatabase.FindAssets("t:Prefab");
            int fixedCount = 0;
            int errorCount = 0;

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);

                if (prefab != null && prefab.GetComponent<WeaponSystem>() != null)
                {
                    if (FixWeaponPrefab(prefab, path))
                    {
                        fixedCount++;
                    }
                    else
                    {
                        errorCount++;
                    }
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog(
                "Fix Complete",
                $"✅ Fixed: {fixedCount} prefabs\n" +
                $"❌ Errors: {errorCount} prefabs\n\n" +
                "All changes saved.",
                "OK"
            );

            Debug.Log($"✅ [WeaponPrefabFixer] Fixed {fixedCount} weapon prefabs");
        }

        private void FixSelectedPrefabs()
        {
            int fixedCount = 0;

            foreach (GameObject obj in Selection.gameObjects)
            {
                if (obj.GetComponent<WeaponSystem>() != null)
                {
                    string path = AssetDatabase.GetAssetPath(obj);
                    if (!string.IsNullOrEmpty(path))
                    {
                        if (FixWeaponPrefab(obj, path))
                        {
                            fixedCount++;
                        }
                    }
                }
            }

            if (fixedCount > 0)
            {
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
            }

            EditorUtility.DisplayDialog(
                "Fix Complete",
                $"✅ Fixed: {fixedCount} prefabs",
                "OK"
            );
        }

        private bool FixWeaponPrefab(GameObject prefab, string path)
        {
            try
            {
                // Check if already has NetworkIdentity
                if (prefab.GetComponent<NetworkIdentity>() != null)
                {
                    Debug.Log($"⏭️ [WeaponPrefabFixer] {prefab.name} already has NetworkIdentity");
                    return false;
                }

                // Add NetworkIdentity
                NetworkIdentity netId = prefab.AddComponent<NetworkIdentity>();
                
                // Configure NetworkIdentity
                // Weapons are usually spawned by server, so serverOnly = false (clients need it too)
                netId.serverOnly = false;
                
                // Note: assetId is automatically generated by Mirror when prefab is registered
                // No need to set it manually

                EditorUtility.SetDirty(prefab);
                Debug.Log($"✅ [WeaponPrefabFixer] Added NetworkIdentity to {prefab.name} ({path})");

                return true;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"❌ [WeaponPrefabFixer] Failed to fix {prefab.name}: {e.Message}");
                return false;
            }
        }
    }
}

